import { api } from "@/lib/api";
import { formatDate } from "@/lib/utils";
import type { Report } from "@/lib/types";

interface ReportDataset {
  rows: Record<string, any>[];
  columns: { key: string; label: string }[];
  preamble: [string, any][];
}

/** Maps each report type to the live collection + columns it should contain. */
const TYPE_SOURCES: Record<
  string,
  { resource: string; sort?: string; columns: { key: string; label: string }[] }
> = {
  security: {
    resource: "security-events",
    sort: "-occurredAt",
    columns: [
      { key: "eventId", label: "Event ID" },
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
      { key: "riskScore", label: "Risk Score" },
      { key: "sourceIp", label: "Source IP" },
      { key: "targetUser", label: "Target User" },
      { key: "targetAsset.assetTag", label: "Target Asset" },
      { key: "occurredAt", label: "Occurred At" },
    ],
  },
  asset: {
    resource: "assets",
    sort: "name",
    columns: [
      { key: "assetTag", label: "Asset Tag" },
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "criticality", label: "Criticality" },
      { key: "environment", label: "Environment" },
      { key: "status", label: "Status" },
      { key: "ipAddress", label: "IP Address" },
      { key: "location", label: "Location" },
      { key: "os", label: "OS" },
      { key: "healthScore", label: "Health Score" },
    ],
  },
  performance: {
    resource: "assets",
    sort: "-healthScore",
    columns: [
      { key: "assetTag", label: "Asset Tag" },
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "environment", label: "Environment" },
      { key: "status", label: "Status" },
      { key: "healthScore", label: "Health Score" },
      { key: "costMonthly", label: "Monthly Cost" },
    ],
  },
  incident: {
    resource: "incidents",
    sort: "-createdAt",
    columns: [
      { key: "incidentId", label: "Incident ID" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "priority", label: "Priority" },
      { key: "status", label: "Status" },
      { key: "category", label: "Category" },
      { key: "commanderName", label: "Commander" },
      { key: "createdAt", label: "Declared At" },
    ],
  },
  maintenance: {
    resource: "maintenance",
    sort: "-createdAt",
    columns: [
      { key: "workOrderId", label: "Work Order" },
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status" },
      { key: "priority", label: "Priority" },
      { key: "assetName", label: "Asset" },
      { key: "assigneeName", label: "Assignee" },
      { key: "scheduledStart", label: "Scheduled Start" },
    ],
  },
  compliance: {
    resource: "assets",
    sort: "criticality",
    columns: [
      { key: "assetTag", label: "Asset Tag" },
      { key: "name", label: "Name" },
      { key: "category", label: "Category" },
      { key: "criticality", label: "Criticality" },
      { key: "environment", label: "Environment" },
      { key: "status", label: "Status" },
      { key: "lifecycleStage", label: "Lifecycle" },
    ],
  },
};

/**
 * Fetches the live dataset a report covers so an export contains real records
 * instead of just the report's metadata.
 */
export async function buildReportDataset(report: Report): Promise<ReportDataset> {
  const source = TYPE_SOURCES[report.type] ?? TYPE_SOURCES.asset;

  const { data } = await api.get(`/${source.resource}`, {
    params: { limit: 500, sort: source.sort },
  });
  let rows: Record<string, any>[] = data.data ?? [];

  // If the report is scoped to specific assets, narrow asset-based datasets.
  const scopeTags = (report.relatedAssets ?? []).map((a) => a.assetTag);
  if (scopeTags.length && (source.resource === "assets")) {
    rows = rows.filter((r) => scopeTags.includes(r.assetTag));
  }

  const preamble: [string, any][] = [
    ["IAETDS Report", report.name],
    ["Report ID", report.reportId],
    ["Type", report.type],
    ["Framework", report.framework || "—"],
    ["Period", report.period],
    ["Status", report.status],
    ["Generated By", report.generatedByName || "—"],
    ["Generated At", report.createdAt ? formatDate(report.createdAt) : "—"],
    ["Scoped Assets", scopeTags.length ? scopeTags.join(" | ") : "All"],
    ["Total Records", rows.length],
    ["Exported At", formatDate(new Date().toISOString())],
  ];

  return { rows, columns: source.columns, preamble };
}
